version: '3.7'
services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
      - '3306:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=postgres
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=password